services:
  - type: web
    name: conte-avec-ia-backend
    env: node
    rootDir: backend
    branch: main
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=450"
    buildCommand: npm install && npm run build && npm prune --production
    startCommand: npm start
